// Acount
// -- actions
export const DO_LOGIN = 'DO_LOGIN'
export const DO_GET_ACCOUNT = 'DO_GET_ACCOUNT'

// -- mutations
export const DO_LOGIN_SUCCESS = 'DO_LOGIN_SUCCESS'
export const SET_ACCOUNT = 'SET_ACCOUNT'

// Scenario
// -- actions
export const DO_GET_BANNERS = 'DO_GET_BANNERS'
export const DO_GET_SCENARIO_DETAIL = 'DO_GET_SCENARIO_DETAIL'

// -- mutations
export const SET_BANNERS = 'SET_BANNERS'
export const SET_SCENARIOS_SELECT = 'SET_SCENARIOS_SELECT'

// order
// -- actions
export const DO_GET_BUYORDER_LIST = 'DO_GET_BUYORDER_LIST'
export const DO_GET_BUYORDER_ITEM = 'DO_GET_BUYORDER_ITEM'
export const DO_DELETE_BUYORDER = 'DO_DELETE_BUYORDER'

// -- mutations
export const SET_BUYORDER_LIST = 'SET_BUYORDER_LIST'
export const SET_BUYORDER_ITEM = 'SET_BUYORDER_ITEM'

// ticket
// -- actions
export const DO_GET_TICKET_GROUP_INFO = 'DO_GET_TICKET_GROUP_INFO'
export const DO_GET_TICKETS = 'DO_GET_TICKETS'
export const DO_GET_DELIVERING_TICKETS = 'DO_GET_DELIVERING_TICKETS'
export const DO_GET_INPICKUP_TICKETS = 'DO_GET_INPICKUP_TICKETS'
export const DO_GET_TICKET_AREA_ROW_COUNT = 'DO_GET_TICKET_AREA_ROW_COUNT'

// -- mutations
export const SET_TICKET_GROUP_INFO = 'SET_TICKET_GROUP_INFO'
export const SET_TICKETS = 'SET_TICKETS'
export const SET_DELIVERING_TICKETS = 'SET_DELIVERING_TICKETS'
export const SET_INPICKUP_TICKETS = 'SET_INPICKUP_TICKETS'
export const SET_TICKET_AREA_ROW_COUNT = 'SET_TICKET_AREA_ROW_COUNT'
